In [1]:
import pandas as pd
data = pd.read_excel('rawData.xlsx')
data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,sajilophone@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rural Municipality/Municipality,Phone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Taplejung,Mayor,NaN,Deputy Mayor,NaN,Chief Executive Officer,NaN,Information Officer,NaN,Office Contact,...,CDO,Police,No Light,Fire,Water,Rescue Services,Airlines,Airports,Mising - Child - Women,मृत्यू कर्म अथवा क्रिया कर्म गर्दा बस्ने स्थानहरू
3,Fungling Municipality,Amir maden,9842660480,Bhima Devi Ojha,9.852660e+09,Tilochan Rimal,9.852622e+09,Bhupal Kumar Sedang,9842660994,024-460114,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Athrai Tribeni Rural Municipality,Dipendra Pomu,9852660958,Shantakumari Angbuhang,9.842659e+09,Bijay Ingnam,9.856061e+09,Ghanshyam Baral,9847322987,9852660960,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 899 entries, 0 to 898
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   843 non-null    object
 1   Unnamed: 1   139 non-null    object
 2   Unnamed: 2   137 non-null    object
 3   Unnamed: 3   138 non-null    object
 4   Unnamed: 4   137 non-null    float64
 5   Unnamed: 5   138 non-null    object
 6   Unnamed: 6   136 non-null    float64
 7   Unnamed: 7   134 non-null    object
 8   Unnamed: 8   133 non-null    object
 9   Unnamed: 9   137 non-null    object
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  826 non-null    object
 12  Unnamed: 12  1 non-null      object
 13  Unnamed: 13  5 non-null      object
 14  Unnamed: 14  2 non-null      object
 15  Unnamed: 15  1 non-null      object
 16  Unnamed: 16  2 non-null      object
 17  Unnamed: 17  1 non-null      object
 18  Unnamed: 18  1 non-null      object
 19  Unnamed: 19  1 non-null      object
 20  Unnamed: 20  1 non-null      object
 21  Unnamed: 21  1 non-null      object
 22  Unnamed: 22  1 non-null      object
 23  Unnamed: 23  1 non-null      object
 24  Unnamed: 24  1 non-null      object
 25  Unnamed: 25  1 non-null      object
dtypes: float64(3), object(23)
memory usage: 182.7+ KB

In [3]:
data.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,sajilophone@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rural Municipality/Municipality,Phone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Taplejung,Mayor,NaN,Deputy Mayor,NaN,Chief Executive Officer,NaN,Information Officer,NaN,Office Contact,...,CDO,Police,No Light,Fire,Water,Rescue Services,Airlines,Airports,Mising - Child - Women,मृत्यू कर्म अथवा क्रिया कर्म गर्दा बस्ने स्थानहरू
3,Fungling Municipality,Amir maden,9842660480,Bhima Devi Ojha,9.852660e+09,Tilochan Rimal,9.852622e+09,Bhupal Kumar Sedang,9842660994,024-460114,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Athrai Tribeni Rural Municipality,Dipendra Pomu,9852660958,Shantakumari Angbuhang,9.842659e+09,Bijay Ingnam,9.856061e+09,Ghanshyam Baral,9847322987,9852660960,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Pathibhara Yangwarak Rural Municipality,Kesharkumar Subba,9842660119,Ranmaya Gurung,9.842660e+09,Janardhan Niraula,9.852660e+09,Raju Gurung,9847395316,9852660460,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Maiwakhola Rural Municipality,Bijayprakash Banem,9852660934,Kamalkumari Limbu,9.852661e+09,Laxmimaya Gomden,9.852661e+09,Madan Tiwari,9849991811,9842691948,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Mikwakhola Rural Municipality,Bhaktabahadur Karki,9842660688,Dandu Lama Sherpa,9.852661e+09,Lalitnarayan Yadav,9.845487e+09,Suman Giri,9852660805,9852660905,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sirijunga Rural Municipality,Lalkrishna Chauhan,9852660331,Chitrakumar Limbu,9.842778e+09,Sky Pokhrel,9.852660e+09,Badriprasad Sitaula,9842781126,9849633951,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Meringden Rural Municipality,Yuk Haam Bir Hamgam(Dambar),9842660467,Durgaprasad Shreng Changwang,9.863818e+09,Arjun Subedi,9.852661e+09,Jiten Limbu,9852660820,9842660822,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.tail(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
889,Bardiya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,Bajura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
891,Achham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
892,Bajhang,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
893,Doti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894,Kailali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
895,Darchula,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,Baitadi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,Dadeldhura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,Kanchanpur,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
data.iloc[168] #last row 168 so total rows needed 169 (0 - 168)
# row 0 and 1 removed as do not have required information

Unnamed: 0     Likhu Pike Rural Municipality
Unnamed: 1                   Minadevi Karki
Unnamed: 2                        9852820030
Unnamed: 3              Dawang Lakpa Sherpa
Unnamed: 4                      9751053966.0
Unnamed: 5                Pushpalal Dhamala
Unnamed: 6                      9852882600.0
Unnamed: 7                     Bhola Basnet
Unnamed: 8                        9849399934
Unnamed: 9                        9852882600
Unnamed: 10                              NaN
Unnamed: 11             लिखु पिके गाउँपालिका
Unnamed: 12                              NaN
Unnamed: 13                              NaN
Unnamed: 14                              NaN
Unnamed: 15                              NaN
Unnamed: 16                              NaN
Unnamed: 17                              NaN
Unnamed: 18                              NaN
Unnamed: 19                              NaN
Unnamed: 20                              NaN
Unnamed: 21                              NaN
Unnamed: 22                              NaN
Unnamed: 23                              NaN
Unnamed: 24                              NaN
Unnamed: 25                              NaN
Name: 168, dtype: object

In [30]:
data = data.iloc[1:169,0:12]
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 151 entries, 2 to 168
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   District                  151 non-null    object
 1   Mayor                     138 non-null    object
 2   MayorNum                  137 non-null    object
 3   DeputyMayor               138 non-null    object
 4   DeputyMayorNum            137 non-null    float64
 5   ChiefExecutiveOfficer     138 non-null    object
 6   ChiefExecutiveOfficerNum  136 non-null    float64
 7   InformationOfficer        134 non-null    object
 8   InformationOfficerNum     133 non-null    object
 9   OfficeContact             137 non-null    object
 10  NepaliDistrictName        136 non-null    object
dtypes: float64(2), object(9)
memory usage: 14.2+ KB

In [22]:
# data.iloc[2]
columnNames = ['District','Mayor','MayorNum','DeputyMayor','DeputyMayorNum','ChiefExecutiveOfficer','ChiefExecutiveOfficerNum','InformationOfficer','InformationOfficerNum','OfficeContact','Delete','NepaliDistrictName']
data.columns = columnNames
data = data.drop('Delete', axis=1)

In [31]:
data = data.dropna(how='all') # remove all NaN row entries
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 151 entries, 2 to 168
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   District                  151 non-null    object
 1   Mayor                     138 non-null    object
 2   MayorNum                  137 non-null    object
 3   DeputyMayor               138 non-null    object
 4   DeputyMayorNum            137 non-null    float64
 5   ChiefExecutiveOfficer     138 non-null    object
 6   ChiefExecutiveOfficerNum  136 non-null    float64
 7   InformationOfficer        134 non-null    object
 8   InformationOfficerNum     133 non-null    object
 9   OfficeContact             137 non-null    object
 10  NepaliDistrictName        136 non-null    object
dtypes: float64(2), object(9)
memory usage: 14.2+ KB

In [33]:
#  Have required column name and row entries , now need to break them down
data.head(15)

,District,Mayor,MayorNum,DeputyMayor,DeputyMayorNum,ChiefExecutiveOfficer,ChiefExecutiveOfficerNum,InformationOfficer,InformationOfficerNum,OfficeContact,NepaliDistrictName
2,Taplejung,Mayor,NaN,Deputy Mayor,NaN,Chief Executive Officer,NaN,Information Officer,NaN,Office Contact,NaN
3,Fungling Municipality,Amir maden,9842660480,Bhima Devi Ojha,9.852660e+09,Tilochan Rimal,9.852622e+09,Bhupal Kumar Sedang,9842660994,024-460114,फुङ्लिङ नगरपालिका
4,Athrai Tribeni Rural Municipality,Dipendra Pomu,9852660958,Shantakumari Angbuhang,9.842659e+09,Bijay Ingnam,9.856061e+09,Ghanshyam Baral,9847322987,9852660960,आठराई त्रिवेणी गाउँपालिका
5,Pathibhara Yangwarak Rural Municipality,Kesharkumar Subba,9842660119,Ranmaya Gurung,9.842660e+09,Janardhan Niraula,9.852660e+09,Raju Gurung,9847395316,9852660460,पाथिभरा याङवरक गाउँपालिका
6,Maiwakhola Rural Municipality,Bijayprakash Banem,9852660934,Kamalkumari Limbu,9.852661e+09,Laxmimaya Gomden,9.852661e+09,Madan Tiwari,9849991811,9842691948,मैवाखोला गाउँपालिका
7,Mikwakhola Rural Municipality,Bhaktabahadur Karki,9842660688,Dandu Lama Sherpa,9.852661e+09,Lalitnarayan Yadav,9.845487e+09,Suman Giri,9852660805,9852660905,मिक्वाखोला गाउँपालिका
8,Sirijunga Rural Municipality,Lalkrishna Chauhan,9852660331,Chitrakumar Limbu,9.842778e+09,Sky Pokhrel,9.852660e+09,Badriprasad Sitaula,9842781126,9849633951,सिरीजङ्घा गाउँपालिका
9,Meringden Rural Municipality,Yuk Haam Bir Hamgam(Dambar),9842660467,Durgaprasad Shreng Changwang,9.863818e+09,Arjun Subedi,9.852661e+09,Jiten Limbu,9852660820,9842660822,मेरिङदेन गाउँपालिका
10,Sidingwa Rural Municipality,Manbahardur Rai,9852681462,Krishnakumari Kadariya,9.842664e+09,Rudraprasad Begha,9.852681e+09,Semant Bhattarai,9862749168,9852660153,सिदिङ्वा गाउँपालिका
11,Faktanglung Rural Municipality,Rajan Limbu,9851204894,Rabin Samra Limbu,9.844648e+09,Nabin Tembe,9.852660e+09,Jaiprasad Rimal,9852660178,021-696491,फक्ताङलुङ गाउँपालिका
13,Panchthar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Fidim Municipality,Mitraprasad Kafle,9852623107,Radhakrishna Neupane,9.852681e+09,Ganeshprasad Dahal,9.852623e+09,Nirmala Dahal,9842670435,024-521107,फिदिम नगरपालिका
15,Miklajung Rural Municipality,Amarraj Makhim,9816975760,Shantakumar Sherma,9.842648e+09,Agniprasad Chamlagain,9.852685e+09,Khagendra Khanal,9852684828,024-412115,मिक्लाजुङ गाउँपालिका
16,Yangwarak Rural Municipality,Bhimbahadur Yongya(Subash),9816001344,Baba Menyangbo,9.816046e+09,Suman Lingden (Limbu),9.852683e+09,Kendra Khanal,9844638548,024-410049,याङवरक गाउँपालिका
17,Falgunanda Rural Municipality,Brijhang Angdembe,9842661260,Thakur Singh Nembwang,9.852681e+09,Nirmal Tumrok,9.852684e+09,Ushab Acharya,9852684385,9852684384,फाल्गुनन्द गाउँपालिका

In [35]:
# Break the dataframe into district parts
# initialize list to store indices
indices = []
# iterate over rows
for i, row in data.iterrows():
    # check if first column is not NaN and all other columns are NaN
    if pd.notna(row['District']) and pd.isna(row.iloc[1:]).all():
        # if condition is True, add the row index to the list of indices
        indices.append(i)

In [119]:
# correction of indices, error due to removal of blank rows and unnecessary rows
indices=[0,10,19,30,46,64,77,85,92,103,113,122,133,142]
indices

[0, 10, 19, 30, 46, 64, 77, 85, 92, 103, 113, 122, 133, 142]

In [120]:
# split dataframe into smaller dataframes based on district
dfs = []
# dfs.append(data.iloc[0:indices[i], :])
for i in range(len(indices)-1):
    dfs.append(data.iloc[indices[i]:indices[i+1], :])

dfs.append(data.iloc[indices[-1]:, :])

In [125]:
#save each district as csv
for df in dfs:
    filename = 'processed_data/'+ str(df.iloc[0,0]) + '.csv'
    df.to_csv(filename, index=False)